import type { SupportOperator } from '#shared/types/support-operator'

/**
 * Mock 輔訓幹員資料，謄寫自 Google Sheet「方舟專精計時器」附件:訓練幹員 分頁（20 筆）。
 * 之後若接上真的資料來源（Google Sheets API／資料庫），只需替換這個模組的內容，
 * server/api/support-operators.get.ts 的篩選邏輯與回傳格式不需變動。
 */
export const supportOperators: SupportOperator[] = [
  {
    id: 'logos',
    name: 'Logos',
    category: 'main',
    skillScope: null,
    efficiencyBonus: 0,
    targetClasses: ['先鋒', '近衛', '特種', '重裝', '醫療', '狙擊'],
    triggersHalfWork: true,
    requiredAccompanyMinutes: 305,
    note: '需要5hr',
  },
  {
    id: 'logos-caster-support',
    name: 'Logos（術/輔）',
    category: 'main_pro',
    skillScope: null,
    efficiencyBonus: 30,
    targetClasses: ['術師', '輔助'],
    triggersHalfWork: true,
    requiredAccompanyMinutes: 305,
    note: '需要5hr',
  },
  {
    id: 'elysium',
    name: '艾麗妮',
    category: 'main',
    skillScope: null,
    efficiencyBonus: 0,
    targetClasses: ['先鋒', '輔助', '特種', '重裝', '醫療', '術師'],
    triggersHalfWork: true,
    requiredAccompanyMinutes: 305,
    note: '需要5hr',
  },
  {
    id: 'elysium-guard-sniper',
    name: '艾麗妮（近/狙）',
    category: 'main_pro',
    skillScope: null,
    efficiencyBonus: 30,
    targetClasses: ['近衛', '狙擊'],
    triggersHalfWork: true,
    requiredAccompanyMinutes: 305,
    note: '需要5hr',
  },
  {
    id: 'ulpianus',
    name: '烏爾比安',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 50,
    targetClasses: ['先鋒', '輔助', '特種', '重裝', '醫療', '術師'],
    triggersHalfWork: false,
    note: '宿舍要帶 3+1 睡覺幹員',
  },
  {
    id: 'ulpianus-guard-support',
    name: '烏爾比安（近/輔）',
    category: 'general_pro',
    skillScope: null,
    efficiencyBonus: 80,
    targetClasses: ['近衛', '輔助'],
    triggersHalfWork: false,
    note: '宿舍要帶 3+1 睡覺幹員',
  },
  {
    id: 'flameshadow-fungus',
    name: '焰影蕈草',
    category: 'general_pro',
    skillScope: null,
    efficiencyBonus: 45,
    targetClasses: ['醫療', '術師'],
    triggersHalfWork: false,
  },
  {
    id: 'heidi',
    name: '黑',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 60,
    targetClasses: ['狙擊'],
    triggersHalfWork: false,
  },
  {
    id: 'hongdou',
    name: '紅豆',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 50,
    targetClasses: ['先鋒'],
    triggersHalfWork: false,
  },
  {
    id: 'ursus-student-2',
    name: '星熊',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 60,
    targetClasses: ['重裝'],
    triggersHalfWork: false,
  },
  {
    id: 'a-mount-elephant',
    name: '阿',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 60,
    targetClasses: ['醫療'],
    triggersHalfWork: false,
  },
  {
    id: 'shalem',
    name: '傀影',
    category: 'general',
    skillScope: null,
    efficiencyBonus: 60,
    targetClasses: ['特種'],
    triggersHalfWork: false,
  },
  {
    id: 'shuichen',
    name: '水陳',
    category: 'skill_specific',
    skillScope: 1,
    efficiencyBonus: 95,
    targetClasses: ['狙擊'],
    triggersHalfWork: false,
    note: '一技能針對',
  },
  {
    id: 'yeban',
    name: '夜半',
    category: 'skill_specific',
    skillScope: 1,
    efficiencyBonus: 75,
    targetClasses: ['先鋒'],
    triggersHalfWork: false,
    note: '一技能針對',
  },
  {
    id: 'texas-taciturnity',
    name: '緘默德克薩斯',
    category: 'skill_specific',
    skillScope: 2,
    efficiencyBonus: 80,
    targetClasses: ['先鋒', '特種'],
    triggersHalfWork: false,
    note: '二技能針對',
  },
  {
    id: 'muelsyse-turbid-lotus',
    name: '濁塵芙蓉',
    category: 'skill_specific',
    skillScope: 2,
    efficiencyBonus: 75,
    targetClasses: ['醫療'],
    triggersHalfWork: false,
    note: '二技能針對',
  },
  {
    id: 'skadi-muddy',
    name: '濁心斯卡蒂',
    category: 'skill_specific',
    skillScope: 3,
    efficiencyBonus: 95,
    targetClasses: ['輔助'],
    triggersHalfWork: false,
    note: '三技能針對',
  },
  {
    id: 'phantom-abyssal-ghost-shark',
    name: '歸溟幽靈鯊',
    category: 'skill_specific',
    skillScope: 3,
    efficiencyBonus: 95,
    targetClasses: ['特種'],
    triggersHalfWork: false,
    note: '三技能針對',
  },
  {
    id: 'gavial-fortified',
    name: '百鍊嘉維爾',
    category: 'skill_specific',
    skillScope: 3,
    efficiencyBonus: 95,
    targetClasses: ['近衛'],
    triggersHalfWork: false,
    note: '三技能針對',
  },
  {
    id: 'wang-yao',
    name: '望',
    category: 'skill_specific',
    skillScope: 3,
    efficiencyBonus: 70,
    targetClasses: ['先鋒', '近衛', '重裝', '狙擊', '術師', '醫療', '輔助', '特種'],
    triggersHalfWork: false,
    note: '三技能針對',
  },
]
